spring:
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health
mybatis:
  mapper-locations: classpath:mapper/*.xml
